import type { Metadata } from "next";
import "../globals.css";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Tolet",
  description: "Generated by create Tahazzee",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col">
        {children}
      </body>
    </html>
  );
}
