import type { Metadata } from "next";
import "../globals.css";
import { cn } from "@/lib/utils";
import { Navbar } from "@/components/shared/Navbar";

export const metadata: Metadata = {
  title: "Tolet",
  description: "Generated by create Tahazzee",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className="min-h-full flex flex-col" >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
